version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: project_management_db
      POSTGRES_USER: axaxab
      POSTGRES_PASSWORD: qwerty123

  backend:
    build: ../project_management
    restart: always
    volumes:
      - static_data:/app/static
      - ../project_management:/app
    depends_on:
      - db
    environment:
      POSTGRES_DB: project_management_db
      POSTGRES_USER: axaxab
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"

  frontend:
    build: ../project-management-frontend
    restart: always
    volumes:
      - ../project-management-frontend:/app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/var/html/static
    depends_on:
      - backend

volumes:
  postgres_data:
  static_data:
